<a href="https://colab.research.google.com/github/yujiimt/Python_tips/blob/main/Valex/Valex_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://qiita.com/simonritchie/items/13b6c1b73d0635a0b54f#from_csv%E9%96%A2%E6%95%B0
!pip install vaex==2.6.1

In [14]:
import vaex
import pandas as pd
import numpy as np

In [5]:
pandas_df = pd.DataFrame(
    data =[{
        "a":1,
        "b":2
    },{
      "a":3,
      "b":4
    }]
)

In [7]:
pandas_df

a  b
0  1  2
1  3  4

In [9]:
vaex_df = vaex.from_pandas(df=pandas_df, copy_index=False)
vaex_df

#    a    b
  0    1    2
  1    3    4

In [10]:
vaex_df["a"]

Expression = a
Length: 2 dtype: int64 (column)
-------------------------------
0  1
1  3

In [11]:
vaex_df.a

Expression = a
Length: 2 dtype: int64 (column)
-------------------------------
0  1
1  3

In [13]:
vaex_df.col.a

Expression = a
Length: 2 dtype: int64 (column)
-------------------------------
0  1
1  3

In [30]:
pandas_df = pd.DataFrame(
    columns = ["x", "y", "z"],
    index = np.arange(0, 3000000))

pandas_df.x = np.random.uniform(low=-100, high = 100, size = len(pandas_df))
pandas_df.y = np.random.uniform(low=0, high=200, size=len(pandas_df))
pandas_df.z = np.random.uniform(low=0, high=1000, size=len(pandas_df))

pandas_df

x           y           z
0        59.982881  175.179774  408.872601
1       -38.088203  199.158753  893.614228
2        47.999103   23.764182  818.482482
3        -6.347350   73.166348  965.123598
4        67.680440   22.274218  344.689697
...            ...         ...         ...
2999995  13.307613  183.854990  106.857612
2999996  83.608648   79.462204  911.466590
2999997 -69.857803   43.402366  525.835645
2999998  60.814145  159.667755  500.605500
2999999  81.505826   17.692489  525.152219

[3000000 rows x 3 columns]

In [31]:
vaex_df = vaex.from_pandas(df = pandas_df, copy_index=False)
vaex_df

#          x                    y                   z
0          59.98288121205414    175.17977371873374  408.87260101272074
1          -38.088202971514676  199.1587533834253   893.6142279349203
2          47.999103314764454   23.764181838007147  818.4824823030982
3          -6.3473501394193335  73.16634797229244   965.123597587113
4          67.68044019308311    22.274217559269395  344.68969669930596
...        ...                  ...                 ...
2,999,995  13.307612989015283   183.8549895359743   106.85761191128806
2,999,996  83.60864809916026    79.46220407493645   911.4665896140563
2,999,997  -69.85780348018405   43.402366152084525  525.8356454052458
2,999,998  60.814145352882576   159.66775545623187  500.6055003034418
2,999,999  81.50582563480444    17.69248947504407   525.1522189054297

In [17]:
numpy_arr = vaex_df.x.values
numpy_arr

array([ 56.45310819, -40.44679273, -66.49806809, ..., -74.92497192,
        91.05372681,  71.89713938])

In [18]:
slice_df = vaex_df[vaex_df.x < 0]

In [19]:
slice_df

#          x                    y                   z
0          -40.446792730281686  97.66297270940191   995.3459041438771
1          -66.49806809203935   52.719191598984835  756.1941755060323
2          -89.08220471485937   147.70654641566915  962.962236082097
3          -28.059848177957193  18.687585283072995  289.7369388199725
4          -1.4999605428447325  104.8879927144291   696.6383774588194
...        ...                  ...                 ...
1,500,709  -9.324216322372905   192.1747552190605   137.85779232064743
1,500,710  -64.29818835720356   86.19236037445603   92.6029814000141
1,500,711  -44.6021004300035    144.58723176745522  935.6584319565975
1,500,712  -28.196632940945605  14.188195107354984  200.99616016188725
1,500,713  -74.92497191563831   144.41016395774972  568.9438743121706

In [20]:
pandas_df = pd.DataFrame(
    data = [{
        "a":60,
        "b":300
    },{
        "a":200,
        "b":50
    },{
        "a":120,
        "b":110
    }])

In [22]:
vaex_df = vaex.from_pandas(df=pandas_df, copy_index=False)
sliced_df = vaex_df[(vaex_df.a > 100) & (vaex_df.a < 150)]
print(sliced_df)

  #    a    b
  0  120  110


In [24]:
sliced_df = vaex_df[(vaex_df.a == 60) | (vaex_df.a == 120)]
print(sliced_df)

  #    a    b
  0   60  300
  1  120  110


In [25]:
sliced_df = vaex_df[~(vaex_df.a == 200)]
print(sliced_df)

  #    a    b
  0   60  300
  1  120  110


In [28]:
print(vaex_df.head(n = 2))

  #    a    b
  0   60  300
  1  200   50


In [32]:
vaex_df.count()

array(3000000)

In [33]:
vaex_df.mean(expression="x")

array(-0.04036918)

In [34]:
vaex_df.x.mean()

array(-0.04036918)

In [35]:
vaex_df.mean(["x", "y"])

array([-4.03691769e-02,  9.99832242e+01])

In [36]:
vaex_df.count(expression=None)

array(3000000)

In [38]:
vaex_df.minmax(expression="x")

array([-99.99996583,  99.99999716])

In [39]:
vaex_df.correlation(x = "x", y = "y")

array(0.00045303)

In [41]:
vaex_df.select(boolean_expression=vaex_df.x > 70)

In [42]:
vaex_df.select(boolean_expression=vaex_df.x > 70, name = "greater_than_70")

In [43]:
vaex_df.minmax(expression=vaex_df.x, selection="greater_than_70")

array([70.00008542, 99.99999716])

In [49]:
sliced_df = vaex_df[vaex_df.x.isin([0, 10])]

In [51]:
pandas_df.to_csv("sample_data.csv", index = False, encoding = "utf-8")

In [52]:
vaex_df = vaex.from_csv("sample_data.csv", copy_index = False)
print(vaex_df)

#          x                    y                   z
0          59.98288121205414    175.17977371873374  408.8726010127208
1          -38.088202971514676  199.15875338342533  893.6142279349202
2          47.999103314764454   23.76418183800715   818.4824823030983
3          -6.3473501394193335  73.16634797229243   965.1235975871131
4          67.6804401930831     22.274217559269395  344.689696699306
...        ...                  ...                 ...
2,999,995  13.307612989015286   183.8549895359743   106.85761191128807
2,999,996  83.60864809916026    79.46220407493645   911.4665896140564
2,999,997  -69.85780348018405   43.40236615208453   525.8356454052458
2,999,998  60.814145352882576   159.66775545623187  500.60550030344183
2,999,999  81.50582563480444    17.69248947504407   525.1522189054297


In [53]:
#pandas 経由で読み込んでるから、読み込み自体は早くならない